//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace dotcover {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Root {
        
        private Assembly[] assemblyField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string dotCoverVersionField;
        
        private string nameField;
        
        private string reportTypeField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Assembly")]
        public Assembly[] Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string DotCoverVersion {
            get {
                return this.dotCoverVersionField;
            }
            set {
                this.dotCoverVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Assembly {
        
        private Namespace[] namespaceField;
        
        private Type[] typeField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Namespace")]
        public Namespace[] Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type")]
        public Type[] Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Namespace {
        
        private Type[] typeField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type")]
        public Type[] Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Type {
        
        private object[] itemsField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constructor", typeof(Constructor))]
        [System.Xml.Serialization.XmlElementAttribute("Event", typeof(Event))]
        [System.Xml.Serialization.XmlElementAttribute("Member", typeof(Member))]
        [System.Xml.Serialization.XmlElementAttribute("Method", typeof(Method))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Property))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(Type))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Constructor {
        
        private object[] itemsField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod", typeof(AnonymousMethod))]
        [System.Xml.Serialization.XmlElementAttribute("OwnCoverage", typeof(OwnCoverage))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AnonymousMethod {
        
        private object[] itemsField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod", typeof(AnonymousMethod))]
        [System.Xml.Serialization.XmlElementAttribute("OwnCoverage", typeof(OwnCoverage))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OwnCoverage {
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Event {
        
        private Method[] methodField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public Method[] Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Method {
        
        private object[] itemsField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod", typeof(AnonymousMethod))]
        [System.Xml.Serialization.XmlElementAttribute("OwnCoverage", typeof(OwnCoverage))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Member {
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Property {
        
        private Method[] methodField;
        
        private string coveragePercentField;
        
        private string coveredStatementsField;
        
        private string nameField;
        
        private string totalStatementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public Method[] Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveragePercent {
            get {
                return this.coveragePercentField;
            }
            set {
                this.coveragePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CoveredStatements {
            get {
                return this.coveredStatementsField;
            }
            set {
                this.coveredStatementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string TotalStatements {
            get {
                return this.totalStatementsField;
            }
            set {
                this.totalStatementsField = value;
            }
        }
    }
}
